CREATE TABLE IF NOT EXISTS people (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    FOREIGN KEY (person) REFERENCES people(id),
    is_incoming INTEGER NOT NULL,
    time TEXT NOT NULL,
    body TEXT NOT NULL
);